// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-nRYaSRYuz3YVWRPofSySqRsEq-LRIVI',
    appId: '1:36147853184:web:ec70071ca729bdf8c07365',
    messagingSenderId: '36147853184',
    projectId: 'this-thing-f97e1',
    authDomain: 'this-thing-f97e1.firebaseapp.com',
    databaseURL: 'https://this-thing-f97e1.firebaseio.com',
    storageBucket: 'this-thing-f97e1.firebasestorage.app',
    measurementId: 'G-8WTKHES29L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBfFMdvd9cV7CmvZThgTqiJrDM0PTV74',
    appId: '1:36147853184:android:e9e3daa8ce692729c07365',
    messagingSenderId: '36147853184',
    projectId: 'this-thing-f97e1',
    databaseURL: 'https://this-thing-f97e1.firebaseio.com',
    storageBucket: 'this-thing-f97e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj8b9vF5bE-6L5aarM6zIK99PY8qvGtM',
    appId: '1:36147853184:ios:3d05021e02367960c07365',
    messagingSenderId: '36147853184',
    projectId: 'this-thing-f97e1',
    databaseURL: 'https://this-thing-f97e1.firebaseio.com',
    storageBucket: 'this-thing-f97e1.firebasestorage.app',
    iosBundleId: 'com.barrocomp.datedash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj8b9vF5bE-6L5aarM6zIK99PY8qvGtM',
    appId: '1:36147853184:ios:3d05021e02367960c07365',
    messagingSenderId: '36147853184',
    projectId: 'this-thing-f97e1',
    databaseURL: 'https://this-thing-f97e1.firebaseio.com',
    storageBucket: 'this-thing-f97e1.firebasestorage.app',
    iosBundleId: 'com.barrocomp.datedash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-nRYaSRYuz3YVWRPofSySqRsEq-LRIVI',
    appId: '1:36147853184:web:3a98a6ebcc252caec07365',
    messagingSenderId: '36147853184',
    projectId: 'this-thing-f97e1',
    authDomain: 'this-thing-f97e1.firebaseapp.com',
    databaseURL: 'https://this-thing-f97e1.firebaseio.com',
    storageBucket: 'this-thing-f97e1.firebasestorage.app',
    measurementId: 'G-QMGRN4KX5S',
  );

}